FROM nginx:1.18.0-alpine

ARG NAME

ARG VERSION

ARG ENV

RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bak

COPY dist/dragon-framework-angular.js /usr/share/nginx/html/dragon-framework-angular.js

COPY nginx/nginx.${ENV}.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
